# Generated by Django 4.1.1 on 2022-11-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('address', models.CharField(default='', max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_off_date', models.DateTimeField()),
                ('drop_off_address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
